// OfficeLink SL — HTML Export (standalone file)

import { render } from '../preview/renderer.js';
import { generateTimestampFilename } from './filename-utils.js';

/**
 * Export rendered markdown as standalone HTML file
 * @param {string} markdownText - Markdown content
 * @param {string} fileName - Base file name
 */
export async function exportHTML(markdownText, fileName = 'document') {
  const html = render(markdownText);
  const standalone = `<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${fileName}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css">
  <style>
    :root {
      --bg: #ffffff;
      --text: #1d1d1f;
      --text-secondary: #6e6e73;
      --border: #e5e5ea;
      --code-bg: #f4f4f8;
      --link: #0071e3;
    }
    @media (prefers-color-scheme: dark) {
      :root {
        --bg: #1c1c1e;
        --text: #f5f5f7;
        --text-secondary: #a1a1a6;
        --border: #38383a;
        --code-bg: #2c2c2e;
        --link: #2997ff;
      }
    }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      max-width: 860px;
      margin: 0 auto;
      padding: 40px 24px;
      background: var(--bg);
      color: var(--text);
      line-height: 1.7;
      font-size: 15px;
    }
    h1, h2, h3, h4, h5, h6 { margin-top: 1.5em; margin-bottom: 0.6em; font-weight: 700; }
    h1 { font-size: 2em; border-bottom: 1px solid var(--border); padding-bottom: 0.3em; }
    h2 { font-size: 1.5em; border-bottom: 1px solid var(--border); padding-bottom: 0.3em; }
    h3 { font-size: 1.25em; }
    p { margin-bottom: 1em; }
    a { color: var(--link); text-decoration: none; }
    a:hover { text-decoration: underline; }
    ul, ol { margin-bottom: 1em; padding-left: 2em; }
    li { margin-bottom: 0.3em; }
    code {
      padding: 0.15em 0.4em;
      font-size: 0.88em;
      background: var(--code-bg);
      border-radius: 4px;
      font-family: 'SF Mono', 'Menlo', monospace;
    }
    pre {
      margin-bottom: 1em;
      padding: 16px;
      overflow-x: auto;
      background: var(--code-bg);
      border-radius: 8px;
      border: 1px solid var(--border);
    }
    pre code { padding: 0; background: transparent; font-size: 0.88em; }
    blockquote {
      margin: 0 0 1em 0;
      padding: 0.5em 1em;
      border-left: 4px solid var(--border);
      color: var(--text-secondary);
    }
    table { width: 100%; margin-bottom: 1em; border-collapse: collapse; }
    th, td { padding: 8px 12px; border: 1px solid var(--border); text-align: left; }
    th { font-weight: 600; }
    hr { height: 2px; margin: 2em 0; background: var(--border); border: none; }
    img { max-width: 100%; border-radius: 8px; }
    .mermaid { text-align: center; margin: 1em 0; }
    @media print {
      body { padding: 0; }
      pre { page-break-inside: avoid; }
    }
  </style>
</head>
<body>
  ${html}
  <hr>
  <p style="text-align:center; font-size:12px; color:var(--text-secondary);">
    Generated by OfficeLink SL — SeouLink
  </p>
</body>
</html>`;

  const defaultName = generateTimestampFilename(fileName, 'html');

  // If File System Access API available, let user choose save location
  if ('showSaveFilePicker' in window) {
    try {
      const handle = await window.showSaveFilePicker({
        suggestedName: defaultName,
        types: [{
          description: 'HTML Files',
          accept: { 'text/html': ['.html'] },
        }],
      });
      const writable = await handle.createWritable();
      await writable.write(standalone);
      await writable.close();
      return;
    } catch (e) {
      if (e.name === 'AbortError') return; // User cancelled
    }
  }

  // Fallback: download with timestamp name
  const blob = new Blob([standalone], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = defaultName;
  a.click();
  URL.revokeObjectURL(url);
}
